//Player object
let jerry = {
  name: 'Jerry Smith',
  health: '1200',
  actions: [
    {
      name: 'Pity Party',
      type: 'attack',
      damage: '18',
      defense: '0',
      timeout: '1000',
      active: true,
      description: 'Cause opponent to feel bad for you.',
    },
    {
      name: 'Fetal Position',
      type: 'defense',
      damage: '0',
      defense: '5',
      timeout: '0',
      active: true,
      description: "But we're Jerry's...",
    },
    {
      name: 'Crawl Away',
      type: 'defense',
      damage: '0',
      defense: '23',
      timeout: '2500',
      active: true,
      description: 'Crawl away from opponent',
    },
    {
      name: 'Plead for mercy',
      type: 'defense',
      damage: '0',
      defense: '9',
      timeout: '1300',
      active: true,
      description: 'Can do!',
    },
    {
      name: 'Pathetic',
      type: 'defense',
      damage: '0',
      defense: '2',
      timeout: '1300',
      active: true,
      description: 'Be pathetic. It helps',
    },
    {
      name: 'Give Effort',
      type: 'defense',
      damage: '0',
      defense: '9',
      timeout: '1300',
      active: true,
      description: "Life is effort and I'll stop when I die!",
    }
  ],
}
