//Player object
let morty = {
  name: 'Morty Smith',
  health: '1200',
  actions: [
    {
      name: 'Purge',
      type: 'attack',
      damage: '50',
      defense: '0',
      timeout: '3500',
      active: true,
      description: 'You just purged morty...',
    },
    {
      name: 'Crash Landing',
      type: 'attack',
      damage: '9',
      defense: '0',
      timeout: '1000',
      active: true,
      description: 'Crash land spaceship into opponent',
    },
    {
      name: 'Weak Threat',
      type: 'attack',
      damage: '9',
      defense: '0',
      timeout: '1000',
      active: true,
      description: 'You may be weak...but you can still do damage!',
    },
    {
      name: 'Cry',
      type: 'defense',
      damage: '0',
      defense: '3',
      timeout: '0',
      active: true,
      description: "Sometimes you just gotta cry it out...",
    },
    {
      name: 'Go Rick',
      type: 'defense',
      damage: '0',
      defense: '18',
      timeout: '2500',
      active: true,
      description: 'Stand behind rick and let him do everything',
    },
    {
      name: 'Mr Meeseeks Destroy!',
      type: 'defense',
      damage: '0',
      defense: '9',
      timeout: '1300',
      active: true,
      description: 'Can do!',
    }
  ],
}
