//Player object
let mrMeeseeks = {
  name: 'Mr Meeseeks',
  health: '1200',
  actions: [
    {
      name: 'Golf',
      type: 'attack',
      damage: '20',
      defense: '0',
      timeout: '3100',
      active: true,
      description: "Take off all of your opponents strokes from their golf game...",
    },
    {
      name: 'Reverse Psychology',
      type: 'attack',
      damage: '7',
      defense: '0',
      timeout: '1000',
      active: true,
      description: 'Provide extremely good advice for your opponent',
    },
    {
      name: 'Exist',
      type: 'attack',
      damage: '16',
      defense: '0',
      timeout: '2100',
      active: true,
      description: 'Existance is pain!!',
    },
    {
      name: 'Immortality',
      type: 'defense',
      damage: '0',
      defense: '17',
      timeout: '1000',
      active: true,
      description: "It's getting weirrrrd",
    },
    {
      name: 'Sheild from law',
      type: 'defense',
      damage: '0',
      defense: '12',
      timeout: '2500',
      active: true,
      description: 'Sheild me from the law',
    },
    {
      name: 'Mr Meeseeks',
      type: 'defense',
      damage: '0',
      defense: '9',
      timeout: '1300',
      active: true,
      description: 'Can do!',
    }
  ],
}
