//Player object
let rick = {
  name: 'Rick Sanchez',
  health: '1200',
  actions: [
    {
      name: 'Particle Watch',
      type: 'attack',
      damage: '12',
      defense: '0',
      active: true,
      timeout: '1000',
      description: 'Particle beam in the wrist watch, snake holster on the leg.',
    },
    {
      name: 'Burp',
      type: 'attack',
      damage: '23',
      defense: '0',
      active: true,
      timeout: '4200',
      description: 'Extreme stank',
    },
    {
      name: 'Blender Portal',
      type: 'attack',
      damage: '17',
      defense: '0',
      active: true,
      timeout: '3000',
      description: 'Open a portal to the blender universe under opponent.',
    },
    {
      name: 'Not Caring',
      type: 'defense',
      damage: '0',
      defense: '7',
      active: true,
      timeout: '1000',
      description: "It's the best.",
    },
    {
      name: 'know It All',
      type: 'defense',
      damage: '0',
      defense: '3',
      active: true,
      timeout: '0',
      description: 'You think I know everything about everything?',
    },
    {
      name: 'Drinking',
      type: 'defense',
      damage: '0',
      defense: '13',
      active: true,
      timeout: '1300',
      description: 'The numbing liquid...',
    },
  ],
}
